demo: use_safetensors to fix vulnerability issue in torch.load
Traceback (most recent call last):
  File "/workspace/DiffusionDemo/run.py", line 22, in <module>
    from src.util import *
  File "/workspace/DiffusionDemo/src/init.py", line 1, in <module>
    from . import util
  File "/workspace/DiffusionDemo/src/util/init.py", line 1, in <module>
    from .base import *
  File "/workspace/DiffusionDemo/src/util/base.py", line 17, in <module>
    from src.util.params import *
  File "/workspace/DiffusionDemo/src/util/params.py", line 83, in <module>
    safety_checker = StableDiffusionSafetyChecker.from_pretrained("CompVis/stable-diffusion-safety-checker")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py", line 309, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4574, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4833, in loadpretrained_model
    load_state_dict(checkpoint_files[0], map_location="meta", weights_only=weights_only).keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/modeling_utils.py", line 554, in load_state_dict
    check_torch_load_is_safe()
  File "/opt/conda/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1417, in check_torch_load_is_safe
    raise ValueError(
ValueError: Due to a serious vulnerability issue in torch.load, even with weights_only=True, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
See the vulnerability report here https://nvd.nist.gov/vuln/detail/CVE-2025-32434